package luvml;

public enum Context {
    PHRASING_CTX, FLOW_CTX, HEAD_CTX, MAP_CTX, TABLE_CTX, TR_CTX, UL_CTX, OL_CTX, DL_CTX, SELECT_CTX, 
    DATALIST_CTX, COLGROUP_CTX, PICTURE_CTX, AUDIO_CTX, VIDEO_CTX, RUBY_CTX, FIGURE_CTX, 
    FIELDSET_CTX, DETAILS_CTX, HTML_CTX, ROOT_CTX
}